package org.primetalk.advent2022

import org.primetalk.advent3.tools.Utils
import org.primetalk.advent3.tools.IDisplay2D
import org.primetalk.advent3.tools.Geom2dUtils._
import scala.collection.immutable.Queue
import org.primetalk.advent3.tools.NumberSequenceUtils

/**
  * https://adventofcode.com/2022/day/23
--- Day 23: Unstable Diffusion ---

You enter a large crater of gray dirt where the grove is supposed to be. All around you, plants you imagine were expected to be full of fruit are instead withered and broken. A large group of Elves has formed in the middle of the grove.

"...but this volcano has been dormant for months. Without ash, the fruit can't grow!"

You look up to see a massive, snow-capped mountain towering above you.

"It's not like there are other active volcanoes here; we've looked everywhere."

"But our scanners show active magma flows; clearly it's going somewhere."

They finally notice you at the edge of the grove, your pack almost overflowing from the random star fruit you've been collecting. Behind you, elephants and monkeys explore the grove, looking concerned. Then, the Elves recognize the ash cloud slowly spreading above your recent detour.

"Why do you--" "How is--" "Did you just--"

Before any of them can form a complete question, another Elf speaks up: "Okay, new plan. We have almost enough fruit already, and ash from the plume should spread here eventually. If we quickly plant new seedlings now, we can still make it to the extraction point. Spread out!"

The Elves each reach into their pack and pull out a tiny plant. The plants rely on important nutrients from the ash, so they can't be planted too close together.

There isn't enough time to let the Elves figure out where to plant the seedlings themselves; you quickly scan the grove (your puzzle input) and note their positions.

For example:

....#..
..###.#
#...#.#
.#...##
#.###..
##.#.##
.#..#..

The scan shows Elves # and empty ground .; outside your scan, more empty ground extends a long way in every direction. The scan is oriented so that north is up; orthogonal directions are written N (north), S (south), W (west), and E (east), while diagonal directions are written NE, NW, SE, SW.

The Elves follow a time-consuming process to figure out where they should each go; you can speed up this process considerably. The process consists of some number of rounds during which Elves alternate between considering where to move and actually moving.

During the first half of each round, each Elf considers the eight positions adjacent to themself. If no other Elves are in one of those eight positions, the Elf does not do anything during this round. Otherwise, the Elf looks in each of four directions in the following order and proposes moving one step in the first valid direction:

    If there is no Elf in the N, NE, or NW adjacent positions, the Elf proposes moving north one step.
    If there is no Elf in the S, SE, or SW adjacent positions, the Elf proposes moving south one step.
    If there is no Elf in the W, NW, or SW adjacent positions, the Elf proposes moving west one step.
    If there is no Elf in the E, NE, or SE adjacent positions, the Elf proposes moving east one step.

After each Elf has had a chance to propose a move, the second half of the round can begin. Simultaneously, each Elf moves to their proposed destination tile if they were the only Elf to propose moving to that position. If two or more Elves propose moving to the same position, none of those Elves move.

Finally, at the end of the round, the first direction the Elves considered is moved to the end of the list of directions. For example, during the second round, the Elves would try proposing a move to the south first, then west, then east, then north. On the third round, the Elves would first consider west, then east, then north, then south.

As a smaller example, consider just these five Elves:

.....
..##.
..#..
.....
..##.
.....

The northernmost two Elves and southernmost two Elves all propose moving north, while the middle Elf cannot move north and proposes moving south. The middle Elf proposes the same destination as the southwest Elf, so neither of them move, but the other three do:

..##.
.....
..#..
...#.
..#..
.....

Next, the northernmost two Elves and the southernmost Elf all propose moving south. Of the remaining middle two Elves, the west one cannot move south and proposes moving west, while the east one cannot move south or west and proposes moving east. All five Elves succeed in moving to their proposed positions:

.....
..##.
.#...
....#
.....
..#..

Finally, the southernmost two Elves choose not to move at all. Of the remaining three Elves, the west one proposes moving west, the east one proposes moving east, and the middle one proposes moving north; all three succeed in moving:

..#..
....#
#....
....#
.....
..#..

At this point, no Elves need to move, and so the process ends.

The larger example above proceeds as follows:

== Initial State ==
..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............

== End of Round 1 ==
..............
.......#......
.....#...#....
...#..#.#.....
.......#..#...
....#.#.##....
..#..#.#......
..#.#.#.##....
..............
....#..#......
..............
..............

== End of Round 2 ==
..............
.......#......
....#.....#...
...#..#.#.....
.......#...#..
...#..#.#.....
.#...#.#.#....
..............
..#.#.#.##....
....#..#......
..............
..............

== End of Round 3 ==
..............
.......#......
.....#....#...
..#..#...#....
.......#...#..
...#..#.#.....
.#..#.....#...
.......##.....
..##.#....#...
...#..........
.......#......
..............

== End of Round 4 ==
..............
.......#......
......#....#..
..#...##......
...#.....#.#..
.........#....
.#...###..#...
..#......#....
....##....#...
....#.........
.......#......
..............

== End of Round 5 ==
.......#......
..............
..#..#.....#..
.........#....
......##...#..
.#.#.####.....
...........#..
....##..#.....
..#...........
..........#...
....#..#......
..............

After a few more rounds...

== End of Round 10 ==
.......#......
...........#..
..#.#..#......
......#.......
...#.....#..#.
.#......##....
.....##.......
..#........#..
....#.#..#....
..............
....#..#..#...
..............

To make sure they're on the right track, the Elves like to check after round 10 that they're making good progress toward covering enough ground. To do this, count the number of empty ground tiles contained by the smallest rectangle that contains every Elf. (The edges of the rectangle should be aligned to the N/S/E/W directions; the Elves do not have the patience to calculate arbitrary rectangles.) In the above example, that rectangle is:

......#.....
..........#.
.#.#..#.....
.....#......
..#.....#..#
#......##...
....##......
.#........#.
...#.#..#...
............
...#..#..#..

In this region, the number of empty ground tiles is 110.

Simulate the Elves' process and find the smallest rectangle that contains the Elves after 10 rounds. How many empty ground tiles does that rectangle contain?

Your puzzle answer was 4045.
--- Part Two ---

It seems you're on the right track. Finish simulating the process and figure out where the Elves need to go. How many rounds did you save them?

In the example above, the first round where no Elf moved was round 20:

.......#......
....#......#..
..#.....#.....
......#.......
...#....#.#..#
#.............
....#.....#...
..#.....#.....
....#.#....#..
.........#....
....#......#..
.......#......

Figure out where the Elves need to go. What is the number of the first round where no Elf moves?

Your puzzle answer was 963.

Both parts of this puzzle are complete! They provide two gold stars: **
  */
object Day2223 extends Utils:

  val input = readThisObjectInput

  // val input = """....#..
  //               |..###.#
  //               |#...#.#
  //               |.#...##
  //               |#.###..
  //               |##.#.##
  //               |.#..#..
  //               |""".stripMargin

  val display = IDisplay2D.readCharDisplayFromString(input)

  val initialElvesPositions =  display.findAll(_ == '#')

  val North: Direction = Down
  val South: Direction = Up
  val West: Direction = Left
  val East: Direction = Right

  val subDirMap = Map(
    North -> List(North, North+West, North+East),
    South -> List(South, South+East, South+West),
    West  -> List(West,  North+West, South+West),
    East  -> List(East,  North+East, South+East),
  )

  val initialValidDirections = Queue(North, South, West, East)

  def step(elves: Seq[Position], directions: List[Direction]): (Seq[Position], Boolean) =
    val elvesSet = elves.toSet
    val plans = elves.map(elf => (elf, 
      if directions8.forall(dir => !elvesSet.contains(elf + dir))
      then 
        None
      else 
        directions.find(
          dir =>
            val checkPositions = subDirMap(dir).map(
              subdir =>
                elf + subdir
            )
            !checkPositions.exists(elvesSet.contains)
        ).map(dir => elf+dir)
    ))
    val (movingPlans, stayingPlans) = plans.partition(_._2.isDefined)
    val movingPlans2 = movingPlans.map{ case (elf, Some(np)) => (elf, np) case _ => ???}

      //.collect{case (elf, Some(p)) => p}
    val inverseMovingPlans = movingPlans2.groupMap(_._2)(_._1)
    val (noCollisions, collisions) = inverseMovingPlans.partition(_._2.length == 1)
    val movingWithoutCollisions = noCollisions
      .map((to, elves) => (to, elves.head))
    val notMovingDueCollisions = collisions.values.flatten
    val moving = movingWithoutCollisions.keys
    val res = stayingPlans.map(_._1) ++ moving ++ notMovingDueCollisions
    //println(IDisplay2D.showPoints(res.toSet, '#', '.').showDisplay()())
    (res, moving.nonEmpty)

  case class State(elves: Seq[Position], dirs: Queue[Direction], hasMoved: Boolean = true):
    def stepS: State =
      val (elves2, hasMoved) = step(elves, dirs.toList)
      val (h, q)= dirs.dequeue
      State(elves2, q.enqueue(h), hasMoved)

  lazy val answer1: Long =
    val state10 = NumberSequenceUtils.unfoldN[State](_.stepS)(State(initialElvesPositions, initialValidDirections), 10)
    //println(IDisplay2D.showPoints(state10.elves.toSet, '#', '.').showDisplay()())
    val r = boundingRect(state10.elves)
    r.area - state10.elves.size

  //Part 2
  lazy val answer2: Int =
    val (last, cnt) = NumberSequenceUtils.countUntil[State](_.stepS)(!_.hasMoved)(State(initialElvesPositions, initialValidDirections))
    cnt

  def main(args: Array[String]): Unit =
    println("Answer1: " + answer1)
    println("Answer2: " + answer2)
